[window]
opacity     = 0.90
decorations = "buttonless"                                                      # No traffic lights, but keeps shape

[font]
normal      = { family = "FiraCode Nerd Font", style = "Regular" }
bold        = { family = "FiraCode Nerd Font", style = "Bold" }
italic      = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size        = 13.0 

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001bb" },                           # Option + ←
  { key = "Right", mods = "Alt", chars = "\u001bf" },                           # Option + →
  { key = "Left",  mods = "Command", chars = "\u001bOH", mode = "AppCursor" },  # Cmd + ← (Home)
  { key = "Right", mods = "Command", chars = "\u001bOF", mode = "AppCursor" },  # Cmd + → (End)
  { key = "Back",  mods = "Command", chars = "\u0015" },                        # Cmd + Backspace (delete line)
  { key = "Back",  mods = "Alt", chars = "\u001b\u007f" }                       # Option + Backspace (delete word)
]

